//go:build darwin

package pdftext

import (
	"strings"
	"testing"
)

// TestExtractFile_Fixture extracts the text layer from a committed test
// document (born-digital, generated by cmd/testdoc) and sanity-checks
// word count, coordinate ranges, and that the canonical title survives
// font-to-Unicode mapping.
func TestExtractFile_Fixture(t *testing.T) {
	pages, err := ExtractFile("../../testdata/ocr-tests/english-single/document.pdf")
	if err != nil {
		t.Fatalf("ExtractFile: %v", err)
	}
	if len(pages) != 1 {
		t.Fatalf("expected 1 page, got %d", len(pages))
	}

	page := pages[0]
	if page.Width <= 0 || page.Height <= 0 {
		t.Fatalf("bad page dimensions: %gx%g", page.Width, page.Height)
	}
	if len(page.Words) < 100 {
		t.Fatalf("expected a full page of words, got %d", len(page.Words))
	}

	var joined strings.Builder
	for _, w := range page.Words {
		if w.Top < 0 || w.Top > 1 || w.Left < 0 || w.Left > 1 ||
			w.Width <= 0 || w.Height <= 0 ||
			w.Top+w.Height > 1.0001 || w.Left+w.Width > 1.0001 {
			t.Fatalf("word %q has out-of-range bounds: %+v", w.Text, w)
		}
		joined.WriteString(w.Text)
		joined.WriteByte(' ')
	}

	// The fixture stores "diﬀerent" with the U+FB00 ligature; NFKC
	// folding must yield the plain form or exact matching fails.
	if !strings.Contains(joined.String(), "different") {
		t.Fatal("ligature folding failed: 'different' not in extracted text")
	}

	blocks := page.Blocks()
	if len(blocks) != len(page.Words) {
		t.Fatalf("Blocks() length %d != words %d", len(blocks), len(page.Words))
	}
	for _, b := range blocks {
		if b.Extractor != Extractor || b.Confidence != 1.0 {
			t.Fatalf("block %q missing extractor/confidence: %+v", b.Text, b)
		}
	}
}

func TestExtractFile_Missing(t *testing.T) {
	if _, err := ExtractFile("no-such-file.pdf"); err == nil {
		t.Fatal("expected error for missing file")
	}
}
